#!/bin/bash
#
# bootstrap
#
# Get ready to develop

set -e

#
# Welcome
#
echo ""
echo "  box-kuromoji-elasticsearch"
echo ""

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit 1
else
  echo "  + Bundler found."
fi

#
# Check for VirtualBox
#
if test $(which virtualbox)
then
  echo "  o VirtualBox found."
else
  echo "  x You need to install VirtualBox."
  echo "    You can download it from https://www.virtualbox.org/wiki/Downloads"
  exit 1
fi

#
# Check for Vagrant
#
if test $(which vagrant)
then
  echo "  o Vagrant found."
else
  echo "  x You need to install Vagrant."
  echo "    You can download it from http://www.vagrantup.com/downloads.html"
  exit 1
fi

#
# Add a Vagrant Box
#
if [[ $(vagrant box list) =~ opscode-ubuntu-12.04 ]]
then
  echo "  + Vagrant box 'opscode-ubuntu-12.04' found."
else
  echo "  + Adding vagrant box 'opscode-ubuntu-12.04'."
  vagrant box add opscode-ubuntu-12.04 \
    http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
fi

#
# Install Gems
#
echo "  + Bootstrapping your Rubies."
bundle install --quiet

#
# Startup instructions
#
echo ""
echo "  Good work. We're ready."

exit 0
