#!/bin/bash
#
# Usage: script/run
#

set -e

# this script should be run in project root
BASE_DIRECTORY=`pwd`
MODE="--rm -it"

if [ $# -eq 1 ]; then
  if [ $1 = "-d" ]; then
    MODE="-d"
  fi
fi

cd ${BASE_DIRECTORY}
docker kill kuromoji-elasticsearch > /dev/null 2>&1 || true
docker rm   kuromoji-elasticsearch > /dev/null 2>&1 || true
docker run \
  ${MODE} \
  --name kuromoji-elasticsearch \
  -p 9200:9200 \
  quay.io/wantedly/kuromoji-elasticsearch:latest
